name: CI

on:
  push:
    branches: [ "**" ]  # Trigger on all branches
  pull_request:
    branches: [ main, develop ]  # PRs targeting main or develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Test Docker build
      run: |
        docker build -t agent-hub:test .
        
    - name: Test Docker run
      run: |
        docker run -d --name test-container -p 8000:8000 agent-hub:test
        sleep 10
        curl -f http://localhost:8000/health
        docker stop test-container
        docker rm test-container